# Generated by Django 4.2.7 on 2023-11-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_report_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
