# Generated by Django 4.2.7 on 2023-11-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_report_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='investmentrecord',
            name='profitLoss',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
